"""The 256/1024/2048-longest-edge WebP thumbnail ladder -- design.md's "Thumbnail
ladder: 256, 1024, 2048", the same three sizes
android/app/.../sync/Thumbnailer.kt generates on-device. Aspect preserved, never
upscaled: a source already smaller than a rung is returned at its own size, same
as the Android client.

Video posters are best-effort: this machine has no ffmpeg (confirmed in this
tool's own development environment), and Pillow alone cannot decode a video
frame. When `ffmpeg` is found on `PATH` at runtime this extracts a poster frame
with it and thumbnails that; when it isn't, video uploads simply carry no
thumbnails at all -- a real, visible gap (a blank timeline tile until some other
client re-derives them) rather than a fabricated placeholder image, and the
importer's own summary report says how many files this affected. See design.md's
"Changing the ladder later": thumbnails are client-generated by design, so there
is no server-side fallback that will ever fill this in on its own.
"""

from __future__ import annotations

import io
import shutil
import subprocess
from dataclasses import dataclass

from PIL import Image

SIZES = (256, 1024, 2048)
WEBP_QUALITY = 82


@dataclass(frozen=True)
class Thumbnail:
    size: int  # the rung (longest edge requested), not necessarily the edge produced
    width: int
    height: int
    bytes_: bytes


def _target_dimensions(width: int, height: int, longest_edge: int) -> tuple[int, int]:
    src_longest = max(width, height)
    if src_longest <= longest_edge:
        return width, height
    scale = longest_edge / src_longest
    return max(1, round(width * scale)), max(1, round(height * scale))


def _ladder_from_image(im: Image.Image) -> list[Thumbnail]:
    im = im.convert("RGB") if im.mode not in ("RGB", "RGBA") else im
    width, height = im.size
    out = []
    for size in SIZES:
        target = _target_dimensions(width, height, size)
        resized = im if target == (width, height) else im.resize(target, Image.LANCZOS)
        buf = io.BytesIO()
        resized.save(buf, format="WEBP", quality=WEBP_QUALITY)
        out.append(Thumbnail(size, target[0], target[1], buf.getvalue()))
    return out


def generate_for_image(path: str) -> list[Thumbnail]:
    with Image.open(path) as im:
        im.load()
        return _ladder_from_image(im)


def ffmpeg_available() -> bool:
    return shutil.which("ffmpeg") is not None


def generate_for_video(path: str, duration_seconds: float | None) -> list[Thumbnail] | None:
    """None when ffmpeg isn't available or extraction fails -- callers must treat
    that as "no thumbnails for this file", not retry or synthesise one."""
    if not ffmpeg_available():
        return None
    # Half a second in, capped at the clip's own length, mirrors Android's
    # Thumbnailer.posterFrameTimeUs reasoning: many encoders' first frame is a
    # black or keyframe-less blank.
    seek = min(duration_seconds / 2, 1.0) if duration_seconds else 0.5
    try:
        proc = subprocess.run(
            [
                "ffmpeg",
                "-v", "error",
                "-ss", f"{seek:.3f}",
                "-i", path,
                "-frames:v", "1",
                "-f", "image2pipe",
                "-vcodec", "png",
                "-",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=60,
            check=True,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError):
        return None
    if not proc.stdout:
        return None
    try:
        with Image.open(io.BytesIO(proc.stdout)) as im:
            im.load()
            return _ladder_from_image(im)
    except Exception:
        return None
